[package]
name = "bf-interpreter"
default-run = "main"
version = "0.1.0"
edition = "2021"
authors = ["Rhelv"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "*"

[profile.dev]
opt-level = 3